/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Prediction */
        post: operations["create_prediction_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Статус сервиса и его зависимостей.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Models */
            models: boolean;
            /** Database */
            database: boolean;
            /** Redis */
            redis: boolean;
        };
        /** HistoryItem */
        HistoryItem: {
            /** Id */
            id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Product Type */
            product_type: string;
            /** Rotational Speed */
            rotational_speed: number;
            /** Torque */
            torque: number;
            /** Tool Wear */
            tool_wear: number;
            /** Air Temperature */
            air_temperature: number;
            /** Process Temperature */
            process_temperature: number;
            /** Is Failure */
            is_failure: boolean;
            /** Failure Probability */
            failure_probability: number;
            /** Failure Type */
            failure_type: string | null;
        };
        /**
         * HistorySource
         * @enum {string}
         */
        HistorySource: "redis" | "db";
        /**
         * PredictionRequest
         * @description Тело POST /predict. Наследует поля и валидацию MachineInput.
         * @example {
         *       "air_temperature": 298.1,
         *       "process_temperature": 308.6,
         *       "product_type": "M",
         *       "rotational_speed": 1551,
         *       "tool_wear": 108,
         *       "torque": 42.8
         *     }
         */
        PredictionRequest: {
            /**
             * Rotational Speed
             * @description Скорость вращения, об/мин
             */
            rotational_speed: number;
            /**
             * Torque
             * @description Крутящий момент, Нм
             */
            torque: number;
            /**
             * Tool Wear
             * @description Износ инструмента, мин
             */
            tool_wear: number;
            /**
             * Air Temperature
             * @description Температура воздуха, K
             */
            air_temperature: number;
            /**
             * Process Temperature
             * @description Температура процесса, K
             */
            process_temperature: number;
            /**
             * Product Type
             * @description Категория продукта
             * @enum {string}
             */
            product_type: "L" | "M" | "H";
        };
        /**
         * PredictionResponse
         * @description Результат POST /predict. Строится прямо из ORM-объекта Prediction.
         */
        PredictionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Failure */
            is_failure: boolean;
            /** Failure Probability */
            failure_probability: number;
            /** Failure Type */
            failure_type: string | null;
            /** Inference Time Ms */
            inference_time_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_prediction_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_history_get: {
        parameters: {
            query?: {
                source?: components["schemas"]["HistorySource"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
